version: '3'

services:
  measurement-db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: measurement_db
    logging:
      options:
        max-size: 500m
  lint:
    image: measurement_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'gofmt -d . > /reports/fmt.txt; if [[ -s /reports/fmt.txt ]]; then exit 1; else exit 0; fi'
    volumes:
      - ./reports:/reports
  tests:
    image: measurement_api
    build:
      context: ..
      dockerfile: ci/Dockerfile
    command: bash -c 'while !</dev/tcp/measurement-db/5432; do sleep 1; done; go test ./... '
    environment:
      MEASUREMENT_SERVICE_DSN: "postgres://postgres:qwerty@measurement-db:5432/measurement_db?sslmode=disable"
    volumes:
      - ./reports:/reports
    depends_on:
      - measurement-db
