name: Test workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run linters
      run: docker-compose -f ci/docker-compose.yml run lint 
    - name: Run tests
      run: docker-compose -f ci/docker-compose.yml run tests
    - uses: actions/upload-artifact@v1
      with:
        name: check_results
        path: reports
